### ISSUE TITLE
Future: add a way for people to upload documents

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-StudentEvaluations#11]
Could use what we have for Appeals Court, but that code is not 100% solid yet. Look into priority and safeguards, or add this once the feature is more mature on the AssemblyLine.

**Comment by CWEmrich** [comment]
I'm not sure where to add this feature. Do people need to add documents early on or should they upload documents after some initial questions have been asked in the interview?

**Comment by nonprofittechy** [comment]
Probably at the end when they are more committed to finishing the process
