### ISSUE TITLE
Ask if the student has an IEP

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-StudentEvaluations#14]
If they do not they will not have a special education contact. So then it will go to the SPED director. We should omit the SPED coordinator questions.

This is for the evaluation request letter--not the independent evaluation. IN that context students will already have an IEP.

**Comment by miabonardi** [comment]
Ask Diana if this is handled by other language

**Comment by miabonardi** [comment]
Do not need to ask this
