### ISSUE TITLE
Combine "Special Education Coordinator" and "Special Education Director" into one question

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-StudentEvaluations#35]
We use both "Coordinator" and "Director" and it is unclear if we are referring to the same person

**Comment by miabonardi** [comment]
Change to: "What is the name of your child's Special Education Director or Special Education Coordinator?"

And do not list title in letter

**Comment by CWEmrich** [comment]
Changed language of question and consolidate question. Still need to take out the title from the letter.
