### ISSUE TITLE
Add Privacy Policy Link

### ISSUE THREAD

**Issue by CWEmrich** [LemmaLegalConsulting/docassemble-StudentEvaluations#43]
https://github.com/LemmaLegalConsulting/docassemble-StudentEvaluations/blob/f1d0d9a8a02cddece96fbaf68bee69955889efaf/docassemble/StudentEvaluations/data/questions/massachusetts_entire_student_record_request.yml#L92-L97

**Comment by miabonardi** [comment]
@nonprofittechy Is the privacy policy the same as GBLS one?

**Comment by miabonardi** [comment]
#26

**Comment by nonprofittechy** [comment]
Yes, this is hosted on the GBLS server. I still need to update that policy to the plain language one
