### ISSUE TITLE
Language section

### ISSUE THREAD

**Issue by CWEmrich** [LemmaLegalConsulting/docassemble-StudentEvaluations#44]
https://github.com/LemmaLegalConsulting/docassemble-StudentEvaluations/blob/f1d0d9a8a02cddece96fbaf68bee69955889efaf/docassemble/StudentEvaluations/data/questions/massachusetts_educational_evaluations_basic_information.yml#L197-L210

From notes: "Do we need this? Won’t we know the preferred language based on the language they have selected to complete the form?; and
2) if there is a reason we do need this, I think it is best to include only the languages available (Spanish, Portuguese, Haitian Creole, and Simplified Chinese)"

**Comment by CWEmrich** [comment]
Further, consider at the beginning of the interview adding language to further contact MAC for assistance

**Comment by miabonardi** [comment]
> Further, consider at the beginning of the interview adding language to further contact MAC for assistance

This seems like a different issue. Create a different issue for this

**Comment by miabonardi** [comment]
> https://github.com/LemmaLegalConsulting/docassemble-StudentEvaluations/blob/f1d0d9a8a02cddece96fbaf68bee69955889efaf/docassemble/StudentEvaluations/data/questions/massachusetts_educational_evaluations_basic_information.yml#L197-L210
> 
> From notes: "Do we need this? Won’t we know the preferred language based on the language they have selected to complete the form?; and 2) if there is a reason we do need this, I think it is best to include only the languages available (Spanish, Portuguese, Haitian Creole, and Simplified Chinese)"

@nonprofittechy (1) I am not sure we should make this assumption that the language they choose to complete the docassemble form is the preferred language for the school request; (2) We need this right now while we wait for more languages; (3) I am unsure we should be limiting the languages.

**Comment by nonprofittechy** [comment]
Correct, different questions. It might be a helper who is using the interview, not the parent.

The list of languages on this question is the most spoken languages in MA, not the list of languages the interview is translated into.

**Comment by CWEmrich** [comment]
#59
