### ISSUE TITLE
Remove 'Not yet in school option' a parent will not need to make request if child not in school

### ISSUE THREAD

**Issue by CWEmrich** [LemmaLegalConsulting/docassemble-StudentEvaluations#45]
https://github.com/LemmaLegalConsulting/docassemble-StudentEvaluations/blob/f1d0d9a8a02cddece96fbaf68bee69955889efaf/docassemble/StudentEvaluations/data/questions/massachusetts_educational_evaluations_basic_information.yml#L295-L300C11

**Comment by miabonardi** [comment]
Delete line 300

- Not yet in school: Not yet in school
