### ISSUE TITLE
Embed video: https://www.youtube.com/watch?v=yGDtWXyRiXA&list=PLLZkb-U9J6d0lfPrwFBR68TF9BTyH95b2

### ISSUE THREAD

**Issue by CWEmrich** [LemmaLegalConsulting/docassemble-StudentEvaluations#46]
https://github.com/LemmaLegalConsulting/docassemble-StudentEvaluations/blob/f1d0d9a8a02cddece96fbaf68bee69955889efaf/docassemble/StudentEvaluations/data/questions/massachusetts_educational_evaluations_request.yml#L38-L40

**Comment by miabonardi** [comment]
@CWEmrich Ask this question in the docassemble slack: "How do I embed a video in a subquestion?"

**Comment by nonprofittechy** [comment]
You can use the `video` modifier:

https://docassemble.org/docs/modifiers.html#video

**Comment by miabonardi** [comment]
> You can use the `video` modifier:
> 
> https://docassemble.org/docs/modifiers.html#video

This was not easy to find in the documentation!

**Comment by miabonardi** [comment]
#29
