### ISSUE TITLE
Should people be able to upload their own document/image of doc?

### ISSUE THREAD

**Issue by CWEmrich** [LemmaLegalConsulting/docassemble-StudentEvaluations#47]
https://github.com/LemmaLegalConsulting/docassemble-StudentEvaluations/blob/f1d0d9a8a02cddece96fbaf68bee69955889efaf/docassemble/StudentEvaluations/data/questions/prs_complaint_interview.yml#L84-L93

**Comment by miabonardi** [comment]
#11
